"""YAML template generators for GitLab CI and GitHub Actions."""


def generate_gitlab_ci(config):
    """Generate .gitlab-ci.yml content."""
    c = config
    node = c["node_version"]
    pm = c["pm"]
    lockfile = pm["lockfile"]
    install_cmd = pm["install"]
    run = c["run_prefix"]
    build_output = c["build_output"]
    scripts = c["scripts"]

    has_lint = scripts.get("lint", False)
    has_test = scripts.get("test", False)
    has_build = scripts.get("build", False)
    has_typecheck = scripts.get("typecheck", False)

    if not has_build:
        raise ValueError("No 'build' script found in package.json. Cannot generate CI config.")

    lines = [
        "# Auto-generated by cicd-init",
        f"# Framework: {c['framework']} | Package Manager: {c['package_manager']} | Node: {node}",
        "",
        "stages:",
    ]

    # Build stages list
    stages = ["install"]
    if has_typecheck:
        stages.append("typecheck")
    if has_lint:
        stages.append("lint")
    if has_test:
        stages.append("test")
    if has_build:
        stages.append("build")

    for stage in stages:
        lines.append(f"  - {stage}")
    lines.append("")

    # Default config
    lines.extend([
        "default:",
        f"  image: node:{node}-alpine",
        "  cache:",
        "    key:",
        "      files:",
        f"        - {lockfile}",
        "    paths:",
        "      - node_modules/",
        "      - .cache/",
        "",
    ])

    # --- Install job ---
    lines.extend([
        "install:",
        "  stage: install",
        "  script:",
        f"    - {install_cmd}",
        "  cache:",
        "    key:",
        "      files:",
        f"      - {lockfile}",
        "    paths:",
        "      - node_modules/",
        "      - .cache/",
        "    policy: pull-push",
        "",
    ])

    needs_chain = ["install"]

    # --- TypeCheck job ---
    if has_typecheck:
        tc_script = scripts.get("typecheck_script", "typecheck")
        lines.extend([
            "typecheck:",
            "  stage: typecheck",
            f"  needs: [{', '.join(needs_chain)}]",
            "  script:",
            f"    - {run} {tc_script}",
            "  cache:",
            "    key:",
            "      files:",
        f"      - {lockfile}",
            "    paths:",
            "      - node_modules/",
            "    policy: pull",
            "",
        ])
        needs_chain.append("typecheck")

    # --- Lint job ---
    if has_lint:
        lines.extend([
            "lint:",
            "  stage: lint",
            f"  needs: [{', '.join(needs_chain)}]",
            "  script:",
            f"    - {run} lint",
            "  cache:",
            "    key:",
            "      files:",
            f"      - {lockfile}",
            "    paths:",
            "      - node_modules/",
            "    policy: pull",
            "",
        ])
        needs_chain.append("lint")

    # --- Test job ---
    if has_test:
        lines.extend([
            "test:",
            "  stage: test",
            f"  needs: [{', '.join(needs_chain)}]",
            "  script:",
            f"    - {run} test -- --coverage --passWithNoTests",
            r"  coverage: '/All files[^|]*\|[^|]*\s+([\d.]+)/'",
            "  cache:",
            "    key:",
            "      files:",
            f"      - {lockfile}",
            "    paths:",
            "      - node_modules/",
            "    policy: pull",
            "",
        ])
        needs_chain.append("test")

    # --- Build job ---
    if has_build:
        build_needs = [n for n in needs_chain if n != "install"]
        if not build_needs:
            build_needs = ["install"]
        lines.extend([
            "build:",
            "  stage: build",
            f"  needs: [{', '.join(build_needs)}]",
            "  script:",
            f"    - {run} build",
            "  artifacts:",
            "    paths:",
            f"      - {build_output}/",
            "    expire_in: 7 days",
            "  cache:",
            "    key:",
            "      files:",
            f"      - {lockfile}",
            "    paths:",
            "      - node_modules/",
            "    policy: pull",
            "",
        ])

    return "\n".join(lines)


def _gha_setup_steps(pm, node_version, gh_cache):
    """Generate GitHub Actions setup steps (checkout + node setup with cache).

    Returns list of properly indented YAML lines (4-space base for step items).
    """
    steps = [
        "    - uses: actions/checkout@v4",
    ]
    # pnpm needs pnpm/action-setup before setup-node
    if pm == "pnpm":
        steps.extend([
            "    - uses: pnpm/action-setup@v4",
            "      with:",
            "        version: 9",
        ])
    steps.extend([
        "    - uses: actions/setup-node@v4",
        "      with:",
        f"        node-version: {node_version}",
    ])
    if gh_cache:
        steps.append(f"        cache: {gh_cache}")
    return steps


def generate_github_actions(config):
    """Generate .github/workflows/ci.yml content."""
    c = config
    node = c["node_version"]
    pm = c["package_manager"]
    pm_data = c["pm"]
    install_cmd = pm_data["install"]
    run = c["run_prefix"]
    build_output = c["build_output"]
    gh_cache = pm_data["gh_cache"]
    scripts = c["scripts"]

    has_lint = scripts.get("lint", False)
    has_test = scripts.get("test", False)
    has_build = scripts.get("build", False)
    has_typecheck = scripts.get("typecheck", False)

    if not has_build:
        raise ValueError("No 'build' script found in package.json. Cannot generate CI config.")

    lines = [
        "# Auto-generated by cicd-init",
        f"# Framework: {c['framework']} | Package Manager: {pm} | Node: {node}",
        "",
        "name: CI",
        "",
        "on:",
        "  push:",
        "    branches: [main, develop]",
        "  pull_request:",
        "    branches: [main]",
        "",
        "concurrency:",
        "  group: ci-${{ github.ref }}",
        "  cancel-in-progress: true",
        "",
        "jobs:",
    ]

    def _job_steps(extra_runs=None):
        """Generate full steps list for a job: setup + install + optional runs."""
        s = _gha_setup_steps(pm, node, gh_cache)
        s.append(f"    - run: {install_cmd}")
        if extra_runs:
            s.extend(extra_runs)
        return s

    # --- TypeCheck job ---
    if has_typecheck:
        tc_script = scripts.get("typecheck_script", "typecheck")
        lines.extend([
            "  typecheck:",
            "    runs-on: ubuntu-latest",
            "    steps:",
        ])
        lines.extend(_job_steps([f"    - run: {run} {tc_script}"]))
        lines.append("")

    # --- Lint job ---
    if has_lint:
        lines.extend([
            "  lint:",
            "    runs-on: ubuntu-latest",
            "    steps:",
        ])
        lines.extend(_job_steps([f"    - run: {run} lint"]))
        lines.append("")

    # --- Test job ---
    if has_test:
        lines.extend([
            "  test:",
            "    runs-on: ubuntu-latest",
            "    steps:",
        ])
        lines.extend(_job_steps([f"    - run: {run} test -- --coverage --passWithNoTests"]))
        lines.append("")

    # --- Build job ---
    if has_build:
        build_needs = []
        if has_typecheck:
            build_needs.append("typecheck")
        if has_lint:
            build_needs.append("lint")
        if has_test:
            build_needs.append("test")

        lines.extend([
            "  build:",
            "    runs-on: ubuntu-latest",
        ])
        if build_needs:
            lines.append(f"    needs: [{', '.join(build_needs)}]")
        lines.extend([
            "    steps:",
        ])
        lines.extend(_job_steps([
            f"    - run: {run} build",
            "    - uses: actions/upload-artifact@v4",
            "      with:",
            "        name: build-${{ github.sha }}",
            f"        path: {build_output}/",
            "        retention-days: 7",
        ]))
        lines.append("")

    return "\n".join(lines)
